// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      //  case TargetPlatform.macOS:
      //    return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABe8PRlf6IKCleQdNFMP4hnNbsD1M9Yb0',
    appId: '1:59776025036:web:976ce1c5c5cbfc30f2dd69',
    messagingSenderId: '59776025036',
    projectId: 'mychat-6293d',
    authDomain: 'mychat-6293d.firebaseapp.com',
    storageBucket: 'mychat-6293d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb0P4lcg6TOf3fA2qFauYAHoe5I9nPv5I',
    appId: '1:59776025036:android:10a63e93786f105af2dd69',
    messagingSenderId: '59776025036',
    projectId: 'mychat-6293d',
    storageBucket: 'mychat-6293d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzZwAJC9bnQxe4jEnDILLAzQeUsgH7fA',
    appId: '1:59776025036:ios:2cf68ac33f8767f4f2dd69',
    messagingSenderId: '59776025036',
    projectId: 'mychat-6293d',
    storageBucket: 'mychat-6293d.appspot.com',
    iosBundleId: 'com.example.myChat',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAXzZwAJC9bnQxe4jEnDILLAzQeUsgH7fA',
  //   appId: '1:59776025036:ios:2cf68ac33f8767f4f2dd69',
  //   messagingSenderId: '59776025036',
  //   projectId: 'mychat-6293d',
  //   storageBucket: 'mychat-6293d.appspot.com',
  //   iosBundleId: 'com.example.myChat',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyABe8PRlf6IKCleQdNFMP4hnNbsD1M9Yb0',
  //   appId: '1:59776025036:web:5f954cbcec590107f2dd69',
  //   messagingSenderId: '59776025036',
  //   projectId: 'mychat-6293d',
  //   authDomain: 'mychat-6293d.firebaseapp.com',
  //   storageBucket: 'mychat-6293d.appspot.com',
  // );
}
